---
- name: Disable AC sleep
  become_user: "{{ cube_client_user }}"
  dconf:
    key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type
    value: "'nothing'"
    state: present
- name: Disable battery sleep
  become_user: "{{ cube_client_user }}"
  dconf:
    key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type
    value: "'nothing'"
    state: present
- name: Disable idle dim
  become_user: "{{ cube_client_user }}"
  dconf:
    key: /org/gnome/settings-daemon/plugins/power/idle-dim
    value: 'false'
    state: present
- name: Set idle delay
  become_user: "{{ cube_client_user }}"
  dconf:
    key: /org/gnome/desktop/session/idle-delay
    value: "uint32 180"
    state: present
- name: Disable lock screen
  become_user: "{{ cube_client_user }}"
  shell: 'gsettings set org.gnome.desktop.screensaver lock-enabled false'
- name: Install gnome-tweaks
  apt: name=gnome-tweaks state=latest
- name: Install git
  apt: name=git state=latest
- name: Clone screenshield extension
  become_user: "{{ cube_client_user }}"
  git:
    repo: https://github.com/lgpasquale/gnome-shell-extension-disable-screenshield.git
    dest: "/home/{{ cube_client_user }}/.local/share/gnome-shell/extensions/disable-screenshield@lgpasquale.com"
- name: Disable screenshield
  become_user: "{{ cube_client_user }}"
  dconf:
    key: /org/gnome/shell/enabled-extensions
    value: "['disable-screenshield@lgpasquale.com']"
    state: present
