---
- name: Install python3
  apt: name=python3 state=latest
- name: Install pip3
  apt: name=python3-pip state=latest
- name: Copy global python requirements file
  copy:
    src: requirements.txt
    dest: /tmp/requirements.txt
- name: Install global python packages
  pip:
    requirements: /tmp/requirements.txt
- name: Remove global python requirements file
  file:
    path: /tmp/requirements.txt
    state: absent
